apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shipwright-manifests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/blairdrummond/argocd-builds.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
